apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spotlight-tb
spec:
  replicas: {{.Values.numReplicas}}
  template:
    metadata:
      labels:
        app: spotlight-iot
    spec:
      containers:
      - name: spotlight-tb
        image: thingsboard/tb
        ports:
        - containerPort: {{.Values.tbPort}}
