apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spotlight-be
spec:
  replicas: {{.Values.numReplicas}}
  template:
    metadata:
      labels:
        app: spotlight-iot
    spec:
      containers:
      - name: spotlight-be
        image:  ghcr.io/notbobutah/spotlight-iot-be:latest
        ports:
        - containerPort: {{.Values.fePort}}
