apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: pg-data-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
status: {}
