name: Create and publish the BE and FE Docker images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-be
  BE_IMAGE_NAME: ${{ github.repository }}-be
  FE_IMAGE_NAME: ${{ github.repository }}-fe
  DB_IMAGE_NAME: ${{ github.repository }}-db

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for BE Docker
        id: bemeta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.BE_IMAGE_NAME }}
          tags: |
             type=ref,event=tag

      - name: Build and push Docker image for BE
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./be
          push: true
          tags: ${{ steps.bemeta.outputs.tags }}
          labels: ${{ steps.bemeta.outputs.labels }}

      - name: Extract metadata for FE Docker
        id: femeta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.FE_IMAGE_NAME }}
          tags: |
             type=ref,event=tag


      - name: Build and push Docker image for FE
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./fe
          push: true
          tags: ${{ steps.femeta.outputs.tags }}
          labels: ${{ steps.femeta.outputs.labels }}

      - name: Extract metadata for Postgres Docker
        id: dbmeta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}
          tags: |
             type=ref,event=tag

      - name: Build and push Docker image for DB
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./database
          push: true
          tags: ${{ steps.dbmeta.outputs.tags }}
          labels: ${{ steps.dbmeta.outputs.labels }}
